FROM denoland/deno:2.9.5

ENV DENO_DIR=/deno-dir

USER root
WORKDIR /app

COPY deno.json ./
COPY shared ./shared
COPY apps/api ./apps/api
COPY apps/dashboard ./apps/dashboard

RUN mkdir -p /deno-dir \
	&& chown -R deno:deno /app /deno-dir

USER deno
WORKDIR /app/apps/dashboard

RUN deno cache src/index.ts

CMD ["task", "start"]
